config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /en|vi/ do
    devise_for :users, controllers: { passwords: 'user/passwords' }

    resources :access_requests, only: %i(new create edit update)
    get 'access_requests/success', to: 'access_requests#success'

    resources :invoices, only: %i(index) do
      post :search, on: :collection
    end

    namespace :admin do
      get '/', to: 'access_requests#index'
      resources :access_requests, only: %i(index show edit update) do
        post :accept, on: :member
        patch :reject, on: :member
      end
      get '/company_invoices', to: 'invoices#by_companies'
      resources :companies, only: %i() do
        resources :invoices, only: %i(show) do
          get '/', to: 'invoices#index', on: :collection, as: 'index'
        end

      end
    end

    namespace :customer do
      get '/', to: 'invoices#index'
      resources :access_tokens, only: %i(index) do
        patch :reset, on: :collection
      end
      resources :invoices, only: %i(index show)
    end

    namespace :api do
      namespace :v1, defaults: {format: :json}  do
        resource :invoices, only: %i(create) do
          patch :cancle, on: :collection
        end
      end
    end
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :company

  enum state: { approved: 0, suspended: 1 }
  enum nem_validate: { pending: 0, validated: 1, not_validated: 2 }

  has_one_attached :pdf

  after_create :check_nem_validate

  private

  def check_nem_validate
    CheckValidateInvoiceJob.set(wait: 600.seconds).perform_later(self)
  end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::ApplicationController
  def by_companies
    @search = Company.includes(:invoices, :invoices_suspended).order(:id).search(params[:q])
    @companies = @search.result.page params[:page]
  end

  def index
    @company = Company.find(params[:company_id])

    @search = @company.invoices.order(:id).search(params[:q])
    @invoices = @search.result.page params[:page]
  end

  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.js { render 'show_modal' }
    end
  end
end

app/controllers/api/v1/invoices_controller.rb
class Api::V1::InvoicesController < Api::V1::BaseApiController

  def create
    data = invoice_service.create invoice_params

    render json: data
  end

  def cancle
    data = invoice_service.cancle params[:id]

    render json: data
  end

  private

  def invoice_params
    params.require(:invoice).permit(:form_identifier, :serial_number, :invoice_number,:invoice_date, :payment_method, :vat_percent, :transaction_id, :hash_data, :pdf, :customer_name, :paid_amount)
  end

  def invoice_service
    @invoice_service ||= Api::V1::InvoiceService.new(current_user)
  end
end

app/controllers/customer/invoices_controller.rb
class Customer::InvoicesController < Customer::ApplicationController
  before_action :set_invoice, only: %i[show]

  def index
    @search = Invoice.search(params[:q])
    @invoices = @search.result.page params[:page]
  end

  def show
    respond_to do |format|
      format.html
      format.js { render 'show_modal' }
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
  end

  def search
    @invoice = Invoice.find_by(transaction_id: params[:invoice][:transaction_id])
  end
end

app/views/admin/invoices/_show.html.slim
.invoice-box.card
  object data="#{url_for @invoice.pdf}" type="application/pdf" width="100%" height="600px"
    embed src="#{url_for @invoice.pdf}" type="application/pdf"

app/views/admin/invoices/by_companies.html.slim
.row
  .col
    .card.shadow
      .card-body.px-lg-5.py-lg-5
        h1 = t('.search_companies')
        = search_form_for @search, url: admin_company_invoices_path, class: 'full-width' do |f|
          .row
            .col-md-6.col-sm-12
              .form-group
                label.form-control-label = t('.company_name')
                = f.text_field :name_cont, class: 'form-control'
            .col-md-6.col-sm-12
              .form-group
                label.form-control-label = t('.tax_identification_number')
                = f.text_field :tax_identification_number_cont, class: 'form-control'

            .col-md-2.col-sm-12
              button.btn.btn-icon.btn-2.btn-primary type="submit"
                span.btn-inner--icon
                  i.fas.fa-search

.row
  .col
    .card.shadow
      .card-header.border-0
        h3.mb-0 = t('.title')
      .table-responsive
        table.table.align-items-center.table-flush
          thead.thead-light
            tr
              th scope="col" = t('.id')
              th scope="col" = t('.company_name')
              th scope="col" = t('.tax_identification_number')
              th scope="col" = t('.legal_representative')
              th scope="col" = t('.total_invoice')
              th scope="col" = t('.cancle_invoice')
              th scope="col" = t('.action')
          tbody
            - @companies.each do |company|
              tr
                td
                  = company.id
                td
                  = company.name
                td
                  = company.tax_identification_number
                td
                  = company.legal_representative
                td
                  = company.invoices.size
                td
                  = company.invoices_suspended.size
                td
                  = link_to t('.detail'), index_admin_company_invoices_path(company)
      = paginate @companies

app/views/admin/invoices/index.html.slim
.row
  .col
    .card.shadow
      .card-body.px-lg-5.py-lg-5
        h1 = t('.search_invoices')
        = search_form_for @search, url: index_admin_company_invoices_path(@company), class: 'full-width' do |f|
          .row
            .col-md-6.col-sm-12
              .form-group
                label.form-control-label = t('.from_date')
                = f.date_field :invoice_date_gteq, class: 'form-control'
              .form-group
                label.form-control-label = t('.to_date')
                = f.date_field :invoice_date_lteq, class: 'form-control'
            .col-md-6.col-sm-12
              .form-group
                label.form-control-label = t('.state')
                = f.select :state_eq, enum_options_for_select(Invoice, :state), include_blank: true

            .col-md-2.col-sm-12
              button.btn.btn-icon.btn-2.btn-primary type="submit"
                span.btn-inner--icon
                  i.fas.fa-search

.row
  .col
    .card.shadow
      .card-header.border-0
        h3.mb-0 = t('.title')
      .table-responsive
        table.table.align-items-center.table-flush
          thead.thead-light
            tr
              th scope="col" = t('.stt')
              th scope="col" = t('.form_identifier')
              th scope="col" = t('.serial_number')
              th scope="col" = t('.invoice_number')
              th scope="col" = t('.name_customer')
              th scope="col" = t('.invoice_date')
              th scope="col" = t('.paid_amount')
              th scope="col" = t('.state')
              th scope="col" = t('.action')
          tbody
            - @invoices.each do |invoice|
              tr
                td
                  = invoice.id
                td
                  = invoice.form_identifier
                td
                  = invoice.serial_number
                td
                  = invoice.invoice_number
                td
                  = invoice.customer_name
                td
                  = invoice.invoice_date
                td
                  = invoice.paid_amount
                td
                  = enum_l(invoice, :state)
                td
                  = link_to t('.detail'), admin_company_invoice_path(@company, invoice), remote: true

      = paginate @invoices

#invoice-modal.modal.fade tabindex="-1"
  .modal-dialog.modal-dialog-centered.modal-lg role="document"
    .modal-content

app/views/admin/invoices/show_modal.js.slim
| $('#invoice-modal .modal-content').html('');
| $('#invoice-modal .modal-content').append("#{j render('admin/invoices/show')}");
| $('#invoice-modal').modal('show')