config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /en|vi/ do
    devise_for :users, controllers: { passwords: 'user/passwords' }

    resources :access_requests, only: %i(new create edit update)
    get 'access_requests/success', to: 'access_requests#success'

    resources :invoices, only: %i(index) do
      post :search, on: :collection
    end

    namespace :admin do
      get '/', to: 'access_requests#index'
      resources :access_requests, only: %i(index show edit update) do
        post :accept, on: :member
        patch :reject, on: :member
      end
      get '/company_invoices', to: 'invoices#by_companies'
      resources :companies, only: %i() do
        resources :invoices, only: %i(show) do
          get '/', to: 'invoices#index', on: :collection, as: 'index'
        end

      end
    end

    namespace :customer do
      get '/', to: 'invoices#index'
      resources :access_tokens, only: %i(index) do
        patch :reset, on: :collection
      end
      resources :invoices, only: %i(index show)
    end

    namespace :api do
      namespace :v1, defaults: {format: :json}  do
        resource :invoices, only: %i(create) do
          patch :cancle, on: :collection
        end
      end
    end
  end
end

app/models/access_request.rb
class AccessRequest < ApplicationRecord
  include AASM

  enum state: { pending: 0, suspended: 1, approved: 2 }

  aasm column: 'state', enum: true do
    state :pending, initial: true
    state :approved, :suspended

    event :approve do
      transitions from: :pending, to: :approved
    end

    event :reject do
      transitions from: :pending, to: :suspended
    end

    event :repending do
      transitions from: :suspended, to: :pending
    end
  end

  has_one_attached :business_registration_certificate
  has_one_attached :certificate_of_tax_registration
  has_one_attached :id_legal_representative_front
  has_one_attached :id_legal_representative_back

  validates_file :business_registration_certificate
  validates_file :certificate_of_tax_registration
  validates_file :id_legal_representative_front
  validates_file :id_legal_representative_back

  validates :company_name, presence: true
  validates :legal_representative, presence: true
  validates :public_address, presence: true, length: { is: 40 }, uniqueness: true
  validates :phone_number, length: { minimum: 10, maximum: 11 }, presence: true
  validates :tax_identification_number, presence: true
  validates :address, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  def image_present?
    self.business_registration_certificate.attached? &&
      self.certificate_of_tax_registration.attached? &&
      self.id_legal_representative_front.attached? &&
      self.id_legal_representative_back.attached?
  end

  class << self
    def generate_token
      loop do
        token = Devise.friendly_token
        break token unless AccessRequest.where(token: token).first
      end
    end
  end
end

app/controllers/access_requests_controller.rb
class AccessRequestsController < ApplicationController
  layout 'devise'

  def new
    @access_request = AccessRequest.new
  end

  def create
    @access_request = AccessRequest.new(access_request_params)

    if @access_request.save
      flash[:success] = t('.created_success')
      redirect_to '/access_requests/success'
    else
      render :new
    end
  end

  def edit
    @access_request = AccessRequest.find_by!(edit_params)
  end

  def update
    @access_request = AccessRequest.find_by(id: params[:id], token: params[:access_request][:token])

    if @access_request.update(access_request_params) && @access_request.may_repending?
      @access_request.repending!
      @access_request.update(reason: nil, token: nil)

      flash[:success] = t('.updated_success')
      redirect_to '/access_requests/success'
    else
      render :edit
    end
  end

  def success
    flash[:success] = t('.created_success')
  end

  private

  def access_request_params
    params.require(:access_request).permit(:company_name, :legal_representative, :phone_number, :tax_identification_number, :address, :email, :user_id, :public_address, :business_registration_certificate, :certificate_of_tax_registration, :id_legal_representative_front, :id_legal_representative_back)
  end

  def edit_params
    params.permit(:id, :token)
  end
end

app/controllers/admin/access_requests_controller.rb
class Admin::AccessRequestsController < Admin::ApplicationController
  before_action :set_access_request, only: %i(show accept reject)

  def index
    @access_requests = AccessRequest.pending.order(:updated_at).page params[:page]
  end

  def show; end

  def accept
    if @access_request.may_approve?

      service.accept(@access_request)

      flash[:success] = t('.accept')
      redirect_to admin_access_requests_path
    end
  end

  def reject
    if @access_request.may_reject?
      @access_request.reject!
      @access_request.token = AccessRequest.generate_token
      @access_request.update(params_request)

      AccessRequestMailer.reject(
        @access_request, I18n.locale.to_s
      ).deliver_later

      flash[:success] = t('.reject')
      redirect_to admin_access_requests_path
    end
  end

  private

  def set_access_request
    @access_request = AccessRequest.find(params[:id])
  end

  def params_request
    params.require(:access_request).permit(:reason)
  end

  def service
    @service ||= Admin::AccessRequestService.new(current_user, I18n.locale)
  end
end

app/views/admin/access_requests/index.html.slim
.row
  .col
    .card.shadow
      .card-header.border-0
        h3.mb-0 = t('.title')
      .table-responsive
        table.table.align-items-center.table-flush
          thead.thead-light
            tr
              th scope="col" = t('.index')
              th scope="col" = t('.company_name')
              th scope="col" = t('.tax_identification_number')
              th scope="col" = t('.legal_representative')
              th scope="col" = t('.phone_number')
              th scope="col" = t('.created_at')
              th scope="col" = t('.action')
          tbody
            - @access_requests.each do |access_request|
              tr
                td
                  = access_request.id
                td
                  = access_request.company_name
                td
                  = access_request.tax_identification_number
                td
                  = access_request.legal_representative
                td
                  = access_request.phone_number
                td
                  = access_request.created_at
                td
                  = link_to t('.detail'), admin_access_request_path(access_request)
      = paginate @access_requests

app/views/admin/access_requests/show.html.slim
.row
  .col
    .card.shadow.bg-secondary
      .card-body
        h2 = t('access_requests.form.company_information')
        .row
          .col-md-6.col-sm-12
            .form-group
              label.form-control-label = t('place_holder.company_name')
              = text_field_tag "", @access_request.company_name, class: 'form-control form-control-alternative', disabled: true
            .form-group
              label.form-control-label = t('place_holder.legal_representative')
              = text_field_tag "", @access_request.legal_representative, class: 'form-control form-control-alternative', disabled: true
            .form-group
              label.form-control-label = t('place_holder.phone_number')
              = text_field_tag "", @access_request.phone_number, class: 'form-control form-control-alternative', disabled: true
          .col-md-6.col-sm-12
            .form-group
              label.form-control-label = t('place_holder.tax_identification_number')
              = text_field_tag "", @access_request.tax_identification_number, class: 'form-control form-control-alternative', disabled: true
            .form-group
              label.form-control-label = t('place_holder.address')
              = text_field_tag "", @access_request.address, class: 'form-control form-control-alternative', disabled: true
            .form-group
              label.form-control-label = t('place_holder.email')
              = text_field_tag "", @access_request.email, class: 'form-control form-control-alternative', disabled: true
        .row
          .col-md-6.col-sm-12
            - if @access_request.business_registration_certificate.attached?
              = link_to @access_request.business_registration_certificate, data: {fancybox: "gallery", caption: t('place_holder.business_registration_certificate') } do
                = image_tag @access_request.business_registration_certificate.variant(resize: "500x500"), class: 'image-full-width'
            - else
              = image_tag 'errors.jpg', class: 'image-full-width'
            .text-center
              label.form-control-label = t('place_holder.business_registration_certificate')
            - if @access_request.certificate_of_tax_registration.attached?
              = link_to @access_request.certificate_of_tax_registration, data: {fancybox: "gallery", caption: t('place_holder.certificate_of_tax_registration') } do
                = image_tag @access_request.certificate_of_tax_registration.variant(resize: "500x500"), class: 'image-full-width'
            - else
              = image_tag 'errors.jpg', class: 'image-full-width'
            .text-center
              label.form-control-label = t('place_holder.certificate_of_tax_registration')
          .col-md-6.col-sm-12
            - if @access_request.id_legal_representative_front.attached?
              = link_to @access_request.id_legal_representative_front, data: {fancybox: "gallery", caption: t('place_holder.id_legal_representative_front') } do
                = image_tag @access_request.id_legal_representative_front.variant(resize: "500x500"), class: 'image-full-width'
            - else
              = image_tag 'errors.jpg', class: 'image-full-width'
            .text-center
              label.form-control-label = t('place_holder.id_legal_representative_front')
            - if @access_request.id_legal_representative_back.attached?
              = link_to @access_request.id_legal_representative_back, data: {fancybox: "gallery", caption: t('place_holder.id_legal_representative_back')} do
                = image_tag @access_request.id_legal_representative_back.variant(resize: "500x500"), class: 'image-full-width'
            - else
              = image_tag 'errors.jpg', class: 'image-full-width'
            .text-center
              label.form-control-label = t('place_holder.id_legal_representative_back')
        .row.text-center
          .col-md-6.col-sm-12
            = button_to accept_admin_access_request_path(@access_request), method: :path, class: 'btn btn-icon btn-3 btn-primary' do
              span.btn-inner--icon
                i.fas.fa-check
              span.btn-inner--text = t('.accept')
          .col-md-6.col-sm-12
            button.btn.btn-icon.btn-3.btn-primary data-target="#modal-reject" data-toggle="modal" type="button"
              span.btn-inner--icon
                i.fas.fa-ban
              span.btn-inner--text = t('.reject')

#modal-reject.modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" role="dialog" tabindex="-1"
  .modal-dialog.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        .card-body.px-lg-5.py-lg-5
          .text-center.text-muted.mb-4
            small = t('.reason')
          = form_for [:reject, :admin, @access_request] do |f|
            .form-group
              = f.text_area :reason, class: 'form-control', placeholder: "#{t('.input_reason')}", cols: "50", rows: "10"
            .row
              = f.submit t('.submit'), class: 'btn btn-primary btn-lg my-4 btn-full'