config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  scope '(:locale)', locale: /en|vi/ do
    devise_for :users, controllers: { passwords: 'user/passwords' }

    resources :access_requests, only: %i(new create edit update)
    get 'access_requests/success', to: 'access_requests#success'

    resources :invoices, only: %i(index) do
      post :search, on: :collection
    end

    namespace :admin do
      get '/', to: 'access_requests#index'
      resources :access_requests, only: %i(index show edit update) do
        post :accept, on: :member
        patch :reject, on: :member
      end
      get '/company_invoices', to: 'invoices#by_companies'
      resources :companies, only: %i() do
        resources :invoices, only: %i(show) do
          get '/', to: 'invoices#index', on: :collection, as: 'index'
        end

      end
    end

    namespace :customer do
      get '/', to: 'invoices#index'
      resources :access_tokens, only: %i(index) do
        patch :reset, on: :collection
      end
      resources :invoices, only: %i(index show)
    end

    namespace :api do
      namespace :v1, defaults: {format: :json}  do
        resource :invoices, only: %i(create) do
          patch :cancle, on: :collection
        end
      end
    end
  end
end

app/controllers/customer/access_tokens_controller.rb
class Customer::AccessTokensController < Customer::ApplicationController
  def index; end

  def reset
    current_user.change_access_token
    redirect_to customer_access_tokens_path
  end

end

app/controllers/customer/application_controller.rb
class Customer::ApplicationController < ApplicationController
  layout 'customer'
end

app/controllers/customer/dashboards_controller.rb
class Customer::DashboardsController < Customer::ApplicationController
  def index; end
end

app/controllers/customer/invoices_controller.rb
class Customer::InvoicesController < Customer::ApplicationController
  before_action :set_invoice, only: %i[show]

  def index
    @search = Invoice.search(params[:q])
    @invoices = @search.result.page params[:page]
  end

  def show
    respond_to do |format|
      format.html
      format.js { render 'show_modal' }
    end
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

end

app/views/customer/access_tokens/index.html.slim
.row
  .col-xl-8.mb-5.mb-xl-0
    .card.bg-gradient-default.shadow
      .card-header.bg-transparent
        .row.align-items-center
          .col
            h2.text-white.mb-0 API KEY
        .row
          .col-md-6.col-sm-12
            .form-group
              = text_field_tag 'access-token', current_user.access_token , class: 'form-control', placeholder: "#{t('place_holder.company_name')}"
          .col-md-6.col-sm-12
              = button_to 'Reset', reset_customer_access_tokens_path, method: :patch, class: 'btn btn-icon btn-3 btn-primary'